version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ctf_demo_db
    environment:
      POSTGRES_DB: ctfdb
      POSTGRES_USER: ctf_user
      POSTGRES_PASSWORD: password123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: ctf_demo_redis
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctf_demo_web
    depends_on:
      - postgres
      - redis
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=92b75bc9894c4b998ef9f1197f6af56a31c5ea93333333333333333333333333
      - DATABASE_URL=postgresql://ctf_user:password123@postgres:5432/ctfdb
      - REDIS_URL=redis://redis:6379/0
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin123
      - TRUSTED_PROXIES=1
      - PREFERRED_URL_SCHEME=http
      - SESSION_COOKIE_SECURE=False
    ports:
      - "5000:5000"

  nginx:
    image: nginx:stable-alpine
    container_name: ctf_demo_nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Simple default proxy config
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: ctf_demo_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./deployment/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: ctf_demo_grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafanadata:/var/lib/grafana

volumes:
  pgdata:
  grafanadata:
